name: deploy to S3

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: build and deploy to s3
    runs-on: ubuntu-latest
    strategy:
      matrix:
<<<<<<< HEAD
        node-version: [14.x]
=======
        node-version: [12.x]
>>>>>>> 126795bcfe1aaebe5e6574b5690dc9309033184d
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
<<<<<<< HEAD

    - run: npm run build 
    - run: npm run deploy
=======
    
    - run: npm run build --if-present
  
>>>>>>> 126795bcfe1aaebe5e6574b5690dc9309033184d

    - name: s3 sync
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-1'
        AWS_S3_BUCKET: alihapifront
        SOURCE_DIR: 'dist'

<<<<<<< HEAD
 
=======
>>>>>>> 126795bcfe1aaebe5e6574b5690dc9309033184d
