name: Upload Website

on:
 push:
   branches:
   - main

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@master
     with:
      cmd: install #will run `npm run install` command
   - uses: actions/checkout@master
     with:
      cmd: build # will run `npm run build` command
   - uses: jakejarvis/s3-sync-action@master
     with:
       args: --acl public-read --follow-symlinks --delete
     env:
       AWS_S3_BUCKET: alihapifront
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_REGION: 'ap-northeast-1'   # S3のリージョンを指定します
       SOURCE_DIR: 'dist/'

