name: Upload Website

on:
 push:
   branches:
   - main

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@master
   - name: Sync s3
     uses: jakejarvis/s3-sync-action@master
     with:
       args: --acl public-read --follow-symlinks --delete
     env:
       AWS_S3_BUCKET: alihapi
<<<<<<< HEAD
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_REGION: 'ap-northeast-1'   # S3のリージョンを指定します
=======
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
       AWS_REGION: 'ap-northeast-1'   # S3のリージョンを指定します
>>>>>>> 6b0e97e055cbe03f89db221c10d9f7ed1ce861f1
